Test: final beta testing
otherplane/witmon pull request #58
Opened 2021-10-19 19:49 UTC by guidiaz

2021-10-22 11:37 UTC, aesedepece requested changes

2021-10-22 11:37 UTC, aesedepece commented on packages/core/migrations/1_decorators.js
> +      ["Kusama", "<path id='a' d='m21 3h4v3h-1v-2h-3zm-1 2v-1h1v1zm-3 1v-1h3v1zm-2 1v-1h2v1zm-3 1v-1h3v1zm-1 1v-1h1v1zm-2 1v-1h2v1zm-1 1v-1h1v1zm-1 1v-1h1v1zm-2 9v-3h1v-6h1v7h-1v2zm-1 2v-2h1v2zm-1 3v
Instead of deleting the `</defs>` tag, we need to add a `<defs>` tag at the beginning.

2021-10-22 13:22 UTC, aesedepece approved these changes
Looks correct to my mental SVG eye.

2021-10-23 12:47 UTC, mariocao approved these changes

2021-10-25 08:51 UTC, merged